name: GLMS Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      ASPNETCORE_ENVIRONMENT: Development

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore GLMS.Tests/GLMS.Tests.csproj

    - name: Build
      run: dotnet build GLMS.Tests/GLMS.Tests.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test GLMS.Tests/GLMS.Tests.csproj --configuration Release --no-build --verbosity normal
